### ISSUE TITLE
Cannot click on anyting 

### ISSUE THREAD

**Issue by toger5** [pyzahl/Gxsm4#6]
I cannot click on any of the buttons in the main window. Also dragging it around does not work. It seems like the events never really reach the gtk widgets. hovering however does highlight them.

**Comment by stmsfnet** [comment]
Independent of a flatpak or normal meson build, the GXSM4 interface just shows the main window which does not respond to the user ... So I can confirm above described behaviour.

**Comment by stmsfnet** [comment]
Problem is solved is Wayland is deactivated. Please have a look at the README.md in the main directory.
